export const topicData: Record<string, string[]> = {
  "52": [
    "Process Management",
    "Memory Management",
    "File Systems",
    "CPU Scheduling",
    "Concurrency",
    "Deadlocks",
    "Virtual Memory",
    "I/O Management",
    "System Calls",
    "OS Architecture",
    "Virtualization & Containers",
    "Security & Access Control",
    "Fault Tolerance & Reliability",
  ],
  "53": [
    "OSI Model",
    "TCP/IP",
    "Routing",
    "IP Addressing",
    "Network Protocols",
    "Data Link Layer",
    "Transport Layer",
    "Network Security",
    "Wireless Networks",
    "Switching & VLANs",
    "Network Virtualization & SDN",
    "Quality of Service (QoS)",
    "MPLS & Traffic Engineering",
  ],
  "54": [
    "Relational Model",
    "SQL",
    "Normalization",
    "Transactions",
    "Concurrency Control",
    "Indexing",
    "ER Model",
    "Query Optimization",
    "NoSQL",
    "Backup & Recovery",
    "Data Warehousing & OLAP",
    "Backup Strategies & Recovery Models",
    "Distributed Databases",
  ],
  "55": [
    "Arrays",
    "Linked Lists",
    "Stacks & Queues",
    "Trees",
    "Graphs",
    "Hash Tables",
    "Heaps",
    "Tries",
    "Complexity Analysis",
    "Self-Balancing Trees (AVL, Red-Black)",
    "Skip Lists",
    "Sparse & Suffix Trees",
  ],
  "56": [
    "Sorting",
    "Searching",
    "Dynamic Programming",
    "Greedy Algorithms",
    "Divide & Conquer",
    "Backtracking",
    "Graph Algorithms",
    "Complexity Classes",
    "Approximation",
    "Amortized Analysis",
    "Randomized Algorithms",
    "Heuristic Methods",
  ],
  "57": [
    "Instruction Set Architecture",
    "CPU Design",
    "Pipelining",
    "Memory Hierarchy",
    "Cache",
    "Registers",
    "I/O Organization",
    "Microarchitecture",
    "RISC vs CISC",
    "Hardware Security",
    "Low-Power & Energy-Efficient Design",
    "Multicore & Manycore Architectures",
  ],
  "58": [
    "Boolean Algebra",
    "Combinational Circuits",
    "Sequential Circuits",
    "Flip-Flops",
    "Multiplexers & Demultiplexers",
    "Encoders & Decoders",
    "Counters",
    "Registers",
    "Programmable Logic Devices (PLDs, FPGAs)",
    "Digital Signal Processing Basics",
  ],
  "59": [
    "Set Theory",
    "Logic & Propositions",
    "Relations & Functions",
    "Combinatorics",
    "Graph Theory",
    "Proof Techniques",
    "Number Theory",
    "Boolean Functions & Switching Theory",
    "Algebraic Structures (Groups, Rings)",
  ],
  "60": [
    "Finite Automata",
    "Regular Languages",
    "Context-Free Grammars",
    "Pushdown Automata",
    "Turing Machines",
    "Decidability",
    "Complexity Theory",
    "Complexity Hierarchies (P vs NP)",
    "Probabilistic Automata",
  ],
  "61": [
    "Lexical Analysis",
    "Syntax Analysis",
    "Semantic Analysis",
    "Intermediate Code Generation",
    "Code Optimization",
    "Code Generation",
    "Symbol Tables",
    "Runtime Environments",
    "Parser Generators (Yacc, ANTLR)",
    "Garbage Collection Strategies",
  ],
  "62": [
    "SDLC",
    "UML",
    "Agile Methodology",
    "Software Design Patterns",
    "Software Testing",
    "Requirement Engineering",
    "Software Architecture",
    "Version Control",
    "Quality Assurance",
    "DevOps & CI/CD Practices",
    "Software Metrics & Measurement",
    "Risk Management",
  ],
  "63": [
    "Classes & Objects",
    "Inheritance",
    "Polymorphism",
    "Encapsulation",
    "Abstraction",
    "Design Patterns",
    "SOLID Principles",
    "Memory Management & Garbage Collection",
    "Reflection & Annotations",
  ],
  "64": [
    "Data Types",
    "Control Structures",
    "Functions",
    "Pointers",
    "Arrays & Strings",
    "Dynamic Memory",
    "File I/O",
    "Preprocessor",
    "Multithreading (pthreads)",
    "Network Programming (sockets)",
  ],
  "65": [
    "JVM & Bytecode",
    "OOP Concepts",
    "Collections Framework",
    "Exception Handling",
    "Threads & Concurrency",
    "Streams API",
    "Generics",
    "JVM Memory Model & GC Tuning",
    "Functional Programming with Streams & Lambdas",
  ],
  "66": [
    "Data Types",
    "Control Flow",
    "Functions & Lambdas",
    "OOP in Python",
    "Modules & Packages",
    "List Comprehensions",
    "File Handling",
    "Decorators & Context Managers",
    "Asyncio & Concurrency",
  ],
  "67": [
    "Supervised Learning",
    "Unsupervised Learning",
    "Regression",
    "Classification",
    "Clustering",
    "Neural Networks",
    "Model Evaluation",
    "Deep Learning Frameworks",
    "Feature Engineering",
  ],
  "68": [
    "Search Algorithms",
    "Knowledge Representation",
    "Expert Systems",
    "Planning",
    "Machine Learning",
    "Logic & Reasoning",
    "Reinforcement Learning",
    "Probabilistic Graphical Models",
  ],
  "69": [
    "Association Rules",
    "Classification",
    "Clustering",
    "Dimensionality Reduction",
    "Outlier Detection",
    "Evaluation Metrics",
    "Text Mining & NLP Techniques",
    "Time Series Analysis",
  ],
  "70": [
    "Hadoop",
    "MapReduce",
    "Spark",
    "NoSQL",
    "Distributed File Systems",
    "Stream Processing",
    "Data Ingestion (Kafka, Flume)",
    "Data Governance & Lineage",
  ],
  "71": [
    "IaaS",
    "PaaS",
    "SaaS",
    "Virtualization",
    "Containers",
    "Serverless",
    "Cloud Security",
    "Cost Optimization & Billing Models",
    "Cloud Deployment Patterns",
  ],
  "72": [
    "Cryptography",
    "Network Security",
    "Application Security",
    "Vulnerabilities",
    "Risk Management",
    "Security Policies",
    "Intrusion Detection & Prevention",
    "Security Audits & Compliance",
  ],
  "73": [
    "Symmetric Encryption",
    "Asymmetric Encryption",
    "Hash Functions",
    "Digital Signatures",
    "Public Key Infrastructure",
    "Elliptic Curve Cryptography",
    "Quantum-Resistant Schemes",
  ],
  "74": [
    "Consensus Algorithms",
    "Smart Contracts",
    "Distributed Ledger",
    "Cryptographic Hashing",
    "Tokens & ICOs",
    "Consensus Variants (PoS, DPoS)",
    "Layer-2 Scaling Solutions",
  ],
  "75": [
    "Rasterization",
    "Rendering",
    "Shaders",
    "Modeling",
    "Animation",
    "Ray Tracing",
    "GPU Programming & GPGPU",
    "Real-Time Rendering Techniques",
  ],
  "76": [
    "Filtering",
    "Edge Detection",
    "Morphological Operations",
    "Transform Techniques",
    "Segmentation",
    "Feature Extraction",
    "Deep Learning for Image Analysis",
    "Feature Matching & Object Tracking",
  ],
  "77": [
    "Image Recognition",
    "Object Detection",
    "Feature Matching",
    "Deep Learning in CV",
    "3D Reconstruction",
    "3D Vision & Point Cloud Processing",
    "SLAM (Simultaneous Localization and Mapping)",
  ],
  "78": [
    "Tokenization",
    "POS Tagging",
    "Syntax & Parsing",
    "Sentiment Analysis",
    "Word Embeddings",
    "Language Models",
    "Transformer Architectures",
    "Language Generation",
  ],
  "79": [
    "Indexing",
    "Boolean Retrieval",
    "Vector Space Model",
    "Ranking Algorithms",
    "Search Engines",
    "Search Personalization",
    "Relevance Feedback",
  ],
  "80": [
    "Usability Principles",
    "User-Centered Design",
    "Prototyping",
    "Accessibility",
    "Interaction Models",
    "User Research & Usability Testing",
    "Eye-Tracking & Gesture Interfaces",
  ],
  "81": [
    "Sensor Networks",
    "Embedded Systems",
    "Communication Protocols",
    "Edge Computing",
    "Security in IoT",
    "MQTT & CoAP Protocols",
    "IoT Data Analytics",
  ],
  "82": [
    "Mobile OS",
    "App Architecture",
    "Resource Management",
    "Connectivity",
    "Security",
    "Energy-Efficient Algorithms",
    "Mobile Security",
  ],
  "83": [
    "Parallel Architectures",
    "Shared vs Distributed Memory",
    "Synchronization",
    "MPI & OpenMP",
    "Performance Metrics",
    "GPU & Accelerator-Based Parallelism",
    "Load Balancing Techniques",
  ],
  "84": [
    "Consistency Models",
    "Replication",
    "Distributed Algorithms",
    "Fault Tolerance",
    "CAP Theorem",
    "Consensus Protocols (Raft, Paxos)",
    "Service Discovery",
  ],
  "85": [
    "Qubits",
    "Quantum Gates",
    "Quantum Algorithms",
    "Entanglement",
    "Superposition",
    "Quantum Error Correction",
    "Quantum Cryptography Basics",
  ],
  "86": [
    "Microcontrollers",
    "RTOS",
    "Hardware Interfacing",
    "Embedded C",
    "Sensors & Actuators",
    "Real-Time Scheduling",
    "Power Management",
  ],
  "87": [
    "Kinematics",
    "Dynamics",
    "Control Systems",
    "Perception",
    "Path Planning",
    "SLAM & Localization",
  ],
  "88": [
    "HTML & CSS",
    "JavaScript",
    "HTTP & REST",
    "Front-End Frameworks",
    "Back-End Frameworks",
    "Web Security (XSS, CSRF)",
    "Progressive Web Apps (PWA)",
  ],
  "89": [
    "Front-End",
    "Back-End",
    "Databases",
    "APIs",
    "Deployment",
    "API Versioning",
    "Microservices Architecture",
  ],
  "90": [
    "CI/CD",
    "Containerization",
    "Infrastructure as Code",
    "Monitoring",
    "Configuration Management",
    "Infrastructure as Code (Terraform, Ansible)",
    "Observability & Tracing",
  ],
  "91": [
    "Penetration Testing",
    "Vulnerability Assessment",
    "Security Tools",
    "Social Engineering",
    "Reporting",
    "Wireless & IoT Pen-testing",
    "Social Engineering Countermeasures",
  ],
  "92": [
    "3D Rendering",
    "Tracking",
    "Interaction Design",
    "Head-Mounted Displays",
    "Spatial Audio & Haptics",
    "UX for Immersive Environments",
  ],
  "93": [
    "Game Engines",
    "Rendering",
    "Physics Simulation",
    "AI in Games",
    "Asset Management",
    "Physics Engines",
    "Networking for Multiplayer",
  ],
  "94": [
    "Unit Testing",
    "Integration Testing",
    "System Testing",
    "Acceptance Testing",
    "Automation",
    "Test-Driven Development (TDD)",
    "Performance & Load Testing",
  ],
  "95": [
    "Access Control",
    "Authentication",
    "Encryption",
    "Security Policies",
    "Incident Response",
    "Digital Forensics",
    "Identity & Access Management",
  ],
  "96": [
    "Interpolation",
    "Numerical Integration",
    "Solving Equations",
    "Error Analysis",
    "Linear Algebra Methods",
    "Eigenvalue Problems",
    "Partial Differential Equation Solvers",
  ],
  "97": [
    "Complexity Analysis",
    "Divide & Conquer",
    "Greedy Methods",
    "Dynamic Programming",
    "Graph Algorithms",
    "Parallel & Distributed Algorithms",
    "Randomized & Quantum Algorithms",
  ],
  "98": [
    "Architecture",
    "Instruction Sets",
    "Peripheral Interfacing",
    "Timers & Interrupts",
    "ARM vs AVR Architectures",
    "Real-Time Operating Systems (RTOS)",
  ],
  "99": [
    "Propositional Logic",
    "Predicate Logic",
    "Set Operations",
    "Relations",
    "Functions",
    "Modal & Predicate Logic Extensions",
  ],
  "100": [
    "Codes of Conduct",
    "IP Rights",
    "Privacy",
    "Compliance",
    "Data Privacy Regulations (GDPR, HIPAA)",
  ],
  "101": [
    "Literature Review",
    "Research Design",
    "Data Collection",
    "Statistical Analysis",
    "Reporting",
    "Experimental Design",
    "Survey & Questionnaire Methods",
  ],
  "102": [
    "HTML & CSS",
    "JavaScript",
    "XML & JSON",
    "HTTP & REST",
    "Web Servers (e.g., Apache)",
    "Client-Side vs Server-Side Scripting",
    "Serverless Architectures",
    "WebSockets & Real-Time Apps",
  ],
  "103": [
    "History & Generations of Computers",
    "Input/Output Devices",
    "Computer Memory (Primary/Secondary)",
    "Software (System/Application)",
    "Number Systems (Binary, Octal, Hex)",
    "Computer Codes (ASCII, BCD)",
    "BIOS/UEFI & Boot Process",
    "Motherboard & Chipset Architecture",
  ],
  "104": [
    "Core C++ Concepts (cin/cout)",
    "OOP in C++",
    "Constructors & Destructors",
    "Inheritance & Polymorphism",
    "Pointers, References & 'this' pointer",
    "Standard Template Library (STL)",
    "Exception Handling",
    "File Handling in C++",
    "Move Semantics & Rvalue References",
    "Template Metaprogramming",
  ],
  "105": [
    "MS Word (Formatting, Mail Merge)",
    "MS Excel (Formulas, Functions, Charts)",
    "MS PowerPoint (Presentations, Animations)",
    "MS Access (Basic Database Concepts)",
    "Macros & VBA",
    "Data Analysis Tools (Pivot Tables)",
  ],
  "106": [
    "Cloud Computing (IaaS, PaaS, SaaS)",
    "Artificial Intelligence & Machine Learning",
    "Internet of Things (IoT)",
    "Big Data Concepts",
    "Edge AI",
    "Digital Twins",
  ],
  "107": [
    "IT Abbreviations & Full Forms",
    "Common File Extensions (.docx, .pdf, .jpg)",
    "Shortcut Keys (OS & MS Office)",
    "Computer Pioneers & Inventions",
    "Internet & Email Terminology (Browser, Search Engine, CC/BCC)",
    "Popular Software & Companies",
    "Emerging IT Standards",
    "Tech Industry Trends",
  ],
};
